name: Run API Tests on Staging Push

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

"on":
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MySpaCover test repo
        uses: actions/checkout@v4
        with:
          repository: yeshsharma/MySpaCover
          token: ${{ secrets.TEST_REPO_SECRET }}
          path: MySpaCover
          ref: ofc-newtestcasesUpdation

      - name: Debug - Show folder structure
        run: |
          echo "Root contents:"
          ls -la
          echo "MySpaCover contents:"
          ls -la MySpaCover/
          echo "Finding pom.xml:"
          find . -name "pom.xml"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run REST Assured Tests
        working-directory: MySpaCover
        run: mvn test
        continue-on-error: true

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extent-report
          path: MySpaCover/test-output/
